"""
2.5D Dogfight HUD Demo: Visualize 3D Error Vector Nullification with Controllers

This script provides an interactive visualization of the upgraded 2.5D environment
where depth perception and multi-target tracking are key features.

What you'll see:
- Green crosshair (center): Your agent - always fixed at center
- Color-coded targets: Multiple targets with depth-based scaling
- Cyan 3D error vector arrow: Points to primary target in 3D space
- Depth indicators: Range display showing z-distance
- HUD display: 3D error (XY + Z breakdown), velocities, lock status
- Agent velocity vector: Shows agent's motion in 3D space (generated by controller)

The agent controls 3D acceleration (ax, ay, az) using PID or Kalman-PID to nullify
the full 3D error vector, including range management via thrust control.

Usage:
    python demo_3d.py pid --n-episodes 3          # 3D PID controller
    python demo_3d.py kalman-pid --n-episodes 3   # 3D Kalman-PID controller
    python demo_3d.py random --num-targets 3      # Random actions (baseline)
"""

import sys
import yaml
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import numpy as np
from environments import make_env
from controllers import PIDAgent3D, KalmanPIDAgent3D, TargetEvaderAgent


def load_config(config_path: str):
    """Load configuration from YAML file."""
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    return config


def run_demo_3d(
    config_path: str = "configs/config.yaml",
    n_episodes: int = 5,
    num_targets: int = 1,
    controller_type: str = "pid",
    use_target_evader: bool = False,
):
    """
    Run a demo of the 2.5D environment with 3D controller.

    Args:
        config_path: Path to configuration file
        n_episodes: Number of episodes to run
        num_targets: Number of targets to spawn
        controller_type: Type of controller ('pid', 'kalman-pid', or 'random')
        use_target_evader: If True, target uses evader PID controller to escape
    """
    # Load configuration
    config = load_config(config_path)

    # Override number of targets
    if "environment" not in config:
        config["environment"] = {}
    config["environment"]["num_targets"] = num_targets

    # Create target controller if requested
    target_controller = None
    if use_target_evader:
        target_controller = TargetEvaderAgent(config)
        print(f"✓ Target evader PID controller enabled!")

    # Create 2.5D environment with rendering
    print(f"\n{'='*60}")
    print(f"2.5D DOGFIGHT HUD DEMO - COMPETITIVE MODE")
    print(f"{'='*60}")
    print(f"Agent Controller: {controller_type.upper()}")
    print(f"Target Behavior: {'EVADER PID (Trying to escape!)' if use_target_evader else 'Brownian + Evasion (Default)'}")
    print(f"Initializing 2.5D environment with {num_targets} target(s)...")
    print(f"Action space: 3D acceleration (ax, ay, az)")
    print(f"Observation: Egocentric view with depth encoding")
    print(f"\nClose the window to stop the demo.\n")

    env = make_env(config, render_mode="human", use_3d=True, target_controller=target_controller)

    # Create controller
    if controller_type.lower() == "pid":
        agent = PIDAgent3D(config)
        agent_name = "3D PID Controller"
    elif controller_type.lower() == "kalman-pid":
        agent = KalmanPIDAgent3D(config)
        agent_name = "3D Kalman-PID Controller"
    else:
        agent = None
        agent_name = "Random Actions"

    for episode in range(n_episodes):
        obs, info = env.reset()

        if agent is not None:
            agent.reset()

        episode_reward = 0
        episode_length = 0
        done = False

        print(f"\n{'='*60}")
        print(f"Episode {episode + 1}/{n_episodes} - {agent_name}")
        print(f"{'='*60}")
        print(f"Targets: {info['num_targets']}")

        while not done:
            # Get action from controller
            if agent is not None:
                action, _ = agent.predict(obs, deterministic=True)
            else:
                # Random actions as fallback
                action = env.action_space.sample()

            # Step environment
            obs, reward, terminated, truncated, info = env.step(action)
            done = terminated or truncated

            episode_reward += reward
            episode_length += 1

            # Render
            env.render()

            # Print info periodically
            if episode_length % 50 == 0:
                distance_3d = info.get("distance_3d", -1)
                distance_xy = info.get("distance_xy", -1)
                distance_z = info.get("distance_z", -1)
                print(f"  Step {episode_length}: 3D Error = {distance_3d:.2f} (XY: {distance_xy:.2f}, Z: {distance_z:.2f})")

        # Episode summary
        print(f"\nEpisode {episode + 1} Summary:")
        print(f"  Total Reward: {episode_reward:.2f}")
        print(f"  Episode Length: {episode_length}")
        print(f"  Final 3D Distance: {info.get('distance_3d', -1):.2f}")

        # Print controller stats
        if agent is not None and hasattr(agent, "get_stats"):
            stats = agent.get_stats()
            print(f"  Detection Rate: {stats['detection_rate']:.1%}")

    env.close()
    print("\nDemo complete!")


def main():
    """Main demo function."""
    parser = argparse.ArgumentParser(
        description="2.5D Dogfight HUD demo with 3D controllers"
    )
    parser.add_argument(
        "controller",
        type=str,
        nargs="?",
        default="pid",
        choices=["pid", "kalman-pid", "random"],
        help="Controller type: pid, kalman-pid, or random",
    )
    parser.add_argument(
        "--config",
        type=str,
        default="configs/config.yaml",
        help="Path to config file",
    )
    parser.add_argument(
        "--n-episodes",
        type=int,
        default=3,
        help="Number of episodes to run",
    )
    parser.add_argument(
        "--num-targets",
        type=int,
        default=1,
        help="Number of targets (1-5)",
    )
    parser.add_argument(
        "--target-evader",
        action="store_true",
        help="Use target evader PID controller (target tries to escape FOV)",
    )

    args = parser.parse_args()

    run_demo_3d(
        config_path=args.config,
        n_episodes=args.n_episodes,
        num_targets=min(args.num_targets, 5),  # Cap at 5
        controller_type=args.controller,
        use_target_evader=args.target_evader,
    )


if __name__ == "__main__":
    main()
